# Generated by Django 3.1 on 2020-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_auto_20200916_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fecha_caducacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='oferta/'),
        ),
    ]
