# Generated by Django 3.1.1 on 2020-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='titulo',
            field=models.ManyToManyField(blank=True, null=True, related_name='matricula_perfilT', through='cuenta.Matricula_Titulo', to='cuenta.Titulo'),
        ),
    ]
