# Generated by Django 3.1.1 on 2020-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_trabajador',
            name='titulo',
            field=models.ManyToManyField(blank=True, related_name='trabajador_titulo', to='cuenta.Titulo'),
        ),
    ]
