# Generated by Django 3.1.1 on 2020-09-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='localidad_provincia', to='cuenta.provincia'),
        ),
        migrations.AlterField(
            model_name='matricula_titulo',
            name='titulo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_de_titulo', to='cuenta.titulo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='localidad',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personas_localidad', to='cuenta.localidad'),
        ),
    ]
