# Generated by Django 3.1.1 on 2020-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20200915_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='localidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='provincia',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
