# Generated by Django 3.1.1 on 2020-09-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_auto_20200913_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_trabajador',
            name='titulo',
            field=models.ManyToManyField(blank=True, related_name='matricula_perfilT', through='cuenta.Matricula_Titulo', to='cuenta.Titulo'),
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='titulo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='en_que_categoria', to='cuenta.titulo'),
        ),
        migrations.AlterField(
            model_name='matricula_titulo',
            name='titulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_de_titulo', to='cuenta.titulo'),
        ),
        migrations.AlterField(
            model_name='matricula_titulo',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula_de_trabajador', to='cuenta.perfil_trabajador'),
        ),
    ]
