# Generated by Django 3.1.1 on 2020-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_perfil_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
