# Generated by Django 3.1.1 on 2020-09-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_auto_20200917_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula_titulo',
            name='titulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricula_de_titulo', to='cuenta.titulo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas_localidad', to='cuenta.localidad'),
        ),
    ]
