# Generated by Django 3.1.1 on 2020-09-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_auto_20200914_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='titulo',
        ),
        migrations.AddField(
            model_name='titulo',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='titulo_de_categoria', to='cuenta.categoria'),
        ),
    ]
