# Generated by Django 3.1.1 on 2020-09-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_auto_20200914_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_trabajador',
            name='recomendaciones',
            field=models.IntegerField(default=0),
        ),
    ]
