# Generated by Django 3.1.1 on 2020-09-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_auto_20200921_1904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula_titulo',
            unique_together={('trabajador', 'titulo')},
        ),
    ]
