# Generated by Django 3.1.1 on 2020-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_auto_20200922_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='facebook',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
