# Generated by Django 3.1.1 on 2020-09-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
        ('cuenta', '0008_auto_20200914_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='titulo_de_categoria', to='bolsa.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
