# Generated by Django 3.1.1 on 2020-09-23 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_auto_20200923_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='recomendaciones',
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendaciones', models.IntegerField(blank=True, max_length=30, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_recomendante', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trabajador', 'cliente')},
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='recomendaciones',
            field=models.ManyToManyField(blank=True, related_name='trabajador_recomendado', through='cuenta.Recomendaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
