# Generated by Django 3.1.1 on 2020-09-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_auto_20200915_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='provincia',
        ),
    ]
