# Generated by Django 3.1.1 on 2020-09-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_auto_20200915_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='localidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personas_por_ciudad', to='cuenta.localidad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='provincia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='personas_por_provincia', to='cuenta.provincia'),
        ),
    ]
