# Generated by Django 3.1.1 on 2020-10-01 22:08

import cuenta.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_auto_20200923_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Que_hacemos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(default='', max_length=10, unique=True, validators=[cuenta.validators.validar_num]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=20, validators=[cuenta.validators.validar_num]),
        ),
    ]
