# Generated by Django 3.1.1 on 2020-10-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0013_auto_20201001_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='que_hacemos',
            old_name='que_podes_hacer',
            new_name='que_es',
        ),
    ]
